branch-defaults:
  default:
    environment: loveletter-dev
    group_suffix: null
deploy:
  artifact: backend.zip
global:
  application_name: loveletter
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
