# This is a basic workflow to help you get started with Actions

name: Build and deploy backend

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
      - '.github/**'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Clean install dependencies and build
      run: |
        npm ci
        npm run build-zip

    - uses: einaregilsson/beanstalk-deploy@v9
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: loveletter-front
        environment_name: ${{ secrets.ENVIRONMENT_NAME }}
        region: us-west-2
        version_label: ${{ github.run_number }}
        deployment_package: backend/backend.zip
